--1. test veritabanınızda employee isimli sütun bilgileri id(INTEGER), name VARCHAR(50), birthday DATE, email VARCHAR(100) olan bir tablo oluşturalım.
CREATE TABLE employee(
	id INTEGER,
	name VARCHAR(50),
	birthday DATE,
	email VARCHAR(100)
);
--2. Oluşturduğumuz employee tablosuna 'Mockaroo' servisini kullanarak 50 adet veri ekleyelim.
insert into employee (id, name, birthday, email) values (1, 'Tammie Tomkys', '1995-02-01', 'ttomkys0@drupal.org');
insert into employee (id, name, birthday, email) values (2, 'Luz Quade', '1981-10-19', 'lquade1@eepurl.com');
insert into employee (id, name, birthday, email) values (3, 'Lorita Toal', '1970-10-30', 'ltoal2@oakley.com');
insert into employee (id, name, birthday, email) values (4, 'Stu O''Fergus', '1978-10-07', 'sofergus3@census.gov');
insert into employee (id, name, birthday, email) values (5, 'Arty Hefford', '2005-01-16', 'ahefford4@gnu.org');
insert into employee (id, name, birthday, email) values (6, 'Jerrylee Castard', '1988-11-28', 'jcastard5@apache.org');
insert into employee (id, name, birthday, email) values (7, 'Leicester Watling', '2008-05-27', 'lwatling6@army.mil');
insert into employee (id, name, birthday, email) values (8, 'Adiana Clemens', '1973-07-15', 'aclemens7@cargocollective.com');
insert into employee (id, name, birthday, email) values (9, 'Stewart Shilito', '1999-01-05', null);
insert into employee (id, name, birthday, email) values (10, 'Viviene Doncaster', '2019-09-16', 'vdoncaster9@elegantthemes.com');
insert into employee (id, name, birthday, email) values (11, 'Coleen Stile', '1991-06-17', 'cstilea@quantcast.com');
insert into employee (id, name, birthday, email) values (12, 'Rosella Giraux', '1977-03-30', 'rgirauxb@harvard.edu');
insert into employee (id, name, birthday, email) values (13, 'Eryn Broadey', '2011-07-14', 'ebroadeyc@cbc.ca');
insert into employee (id, name, birthday, email) values (14, 'Jennilee Hyett', '1997-02-19', 'jhyettd@twitpic.com');
insert into employee (id, name, birthday, email) values (15, 'Jayson Lardiner', '1982-09-13', 'jlardinere@booking.com');
insert into employee (id, name, birthday, email) values (16, 'Uriel Kirk', '2013-05-01', 'ukirkf@reverbnation.com');
insert into employee (id, name, birthday, email) values (17, 'Erick Heimes', '1986-04-16', 'eheimesg@wordpress.org');
insert into employee (id, name, birthday, email) values (18, 'Gerek Whapple', '2016-10-18', null);
insert into employee (id, name, birthday, email) values (19, 'Humphrey Timmens', '2010-09-15', 'htimmensi@icq.com');
insert into employee (id, name, birthday, email) values (20, 'Vin Cardenas', '1992-07-06', 'vcardenasj@godaddy.com');
insert into employee (id, name, birthday, email) values (21, 'Mack Samways', '1979-05-07', 'msamwaysk@theatlantic.com');
insert into employee (id, name, birthday, email) values (22, 'Leshia Saleway', '2018-09-01', 'lsalewayl@gizmodo.com');
insert into employee (id, name, birthday, email) values (23, 'Max Melbourn', '1992-04-18', 'mmelbournm@ucsd.edu');
insert into employee (id, name, birthday, email) values (24, 'Timmy Proudlove', null, 'tproudloven@google.com.au');
insert into employee (id, name, birthday, email) values (25, 'Sky Egalton', '1970-05-24', 'segaltono@nature.com');
insert into employee (id, name, birthday, email) values (26, 'Michele Olerenshaw', '1979-08-11', 'molerenshawp@engadget.com');
insert into employee (id, name, birthday, email) values (27, 'Theobald Androletti', '2017-02-19', null);
insert into employee (id, name, birthday, email) values (28, 'Chery Yoxen', '1988-12-10', 'cyoxenr@prlog.org');
insert into employee (id, name, birthday, email) values (29, 'Golda Ferson', null, null);
insert into employee (id, name, birthday, email) values (30, 'Aurea Lavery', '1972-05-10', 'alaveryt@1und1.de');
insert into employee (id, name, birthday, email) values (31, 'Maggee Stonnell', null, 'mstonnellu@ifeng.com');
insert into employee (id, name, birthday, email) values (32, 'Ruthanne Gornall', '1988-09-10', 'rgornallv@usnews.com');
insert into employee (id, name, birthday, email) values (33, 'Bellina Bugg', '1993-06-01', null);
insert into employee (id, name, birthday, email) values (34, 'Thurstan Dominik', '1978-05-18', null);
insert into employee (id, name, birthday, email) values (35, 'Bridget Burnep', '2005-03-26', 'bburnepy@blogspot.com');
insert into employee (id, name, birthday, email) values (36, 'Nelson Crisall', '1985-08-09', 'ncrisallz@wiley.com');
insert into employee (id, name, birthday, email) values (37, 'Hamlen Grannell', '2008-07-25', 'hgrannell10@japanpost.jp');
insert into employee (id, name, birthday, email) values (38, 'Vanda Antonucci', '2020-07-25', 'vantonucci11@php.net');
insert into employee (id, name, birthday, email) values (39, 'Meghann Killingbeck', '2012-07-21', 'mkillingbeck12@google.com.hk');
insert into employee (id, name, birthday, email) values (40, 'Hersch Habens', '1974-12-21', null);
insert into employee (id, name, birthday, email) values (41, 'Lawton Dobrovolny', '2009-11-12', 'ldobrovolny14@edublogs.org');
insert into employee (id, name, birthday, email) values (42, 'Juana Gutierrez', '1992-01-07', 'jgutierrez15@noaa.gov');
insert into employee (id, name, birthday, email) values (43, 'Renard Adess', '2012-07-10', null);
insert into employee (id, name, birthday, email) values (44, 'Klement Sallarie', '2021-04-10', 'ksallarie17@skyrock.com');
insert into employee (id, name, birthday, email) values (45, 'Nigel Drysdell', '1995-04-03', 'ndrysdell18@state.gov');
insert into employee (id, name, birthday, email) values (46, 'Otto Wybron', '1998-05-01', 'owybron19@buzzfeed.com');
insert into employee (id, name, birthday, email) values (47, 'Halli Crankhorn', '1979-05-01', 'hcrankhorn1a@dyndns.org');
insert into employee (id, name, birthday, email) values (48, 'Myron Dimsdale', '1985-11-29', 'mdimsdale1b@meetup.com');
insert into employee (id, name, birthday, email) values (49, 'Ursula Wyon', '2009-05-16', 'uwyon1c@dot.gov');
insert into employee (id, name, birthday, email) values (50, 'Ambrosius Huddart', '2006-01-17', 'ahuddart1d@slate.com');
insert into employee (id, name, birthday, email) values (51, 'Randell Boughen', null, 'rboughen1e@independent.co.uk');
insert into employee (id, name, birthday, email) values (52, 'Cyrill Smithers', '1992-04-07', 'csmithers1f@diigo.com');
insert into employee (id, name, birthday, email) values (53, 'Lennard Hoston', '2017-12-09', 'lhoston1g@weather.com');
insert into employee (id, name, birthday, email) values (54, 'Abigale Denson', '1997-11-30', 'adenson1h@naver.com');
insert into employee (id, name, birthday, email) values (55, 'Pauly Winsor', '2009-11-07', 'pwinsor1i@unblog.fr');
insert into employee (id, name, birthday, email) values (56, 'Cherey Jahn', '2018-11-26', 'cjahn1j@desdev.cn');
insert into employee (id, name, birthday, email) values (57, 'Ashil Farlambe', '1970-10-06', 'afarlambe1k@cpanel.net');
insert into employee (id, name, birthday, email) values (58, 'Annissa Pobjoy', '2000-10-12', 'apobjoy1l@lulu.com');
insert into employee (id, name, birthday, email) values (59, 'Kelwin Francescotti', '1993-08-17', 'kfrancescotti1m@desdev.cn');
insert into employee (id, name, birthday, email) values (60, 'Talbot Kirman', '1973-11-25', 'tkirman1n@nps.gov');
insert into employee (id, name, birthday, email) values (61, 'Loni Smead', '2006-10-18', null);
insert into employee (id, name, birthday, email) values (62, 'Susanne Anderl', '1980-03-08', 'sanderl1p@theglobeandmail.com');
insert into employee (id, name, birthday, email) values (63, 'Kaye Aspey', '2011-01-21', 'kaspey1q@1und1.de');
insert into employee (id, name, birthday, email) values (64, 'Saxon Bulch', '1982-06-03', 'sbulch1r@gov.uk');
insert into employee (id, name, birthday, email) values (65, 'Regen Shermar', '1971-02-09', 'rshermar1s@cpanel.net');
insert into employee (id, name, birthday, email) values (66, 'Bronny Shafto', '1989-03-02', 'bshafto1t@alexa.com');
insert into employee (id, name, birthday, email) values (67, 'Jacintha Holberry', '2016-04-05', null);
insert into employee (id, name, birthday, email) values (68, 'Ambur Ailsbury', '2003-06-21', 'aailsbury1v@deviantart.com');
insert into employee (id, name, birthday, email) values (69, 'Bearnard Adhams', '1982-11-13', null);
insert into employee (id, name, birthday, email) values (70, 'Rafe Bahia', '2007-08-05', 'rbahia1x@sakura.ne.jp');
insert into employee (id, name, birthday, email) values (71, 'Ardisj Mateja', '1983-06-12', null);
insert into employee (id, name, birthday, email) values (72, 'Alfonso Mariolle', '1983-07-17', 'amariolle1z@instagram.com');
insert into employee (id, name, birthday, email) values (73, 'Neale Mauger', '1999-11-25', 'nmauger20@friendfeed.com');
insert into employee (id, name, birthday, email) values (74, 'Rurik Longmaid', '2020-08-07', 'rlongmaid21@prweb.com');
insert into employee (id, name, birthday, email) values (75, 'Leicester Nichol', '1981-10-11', 'lnichol22@weibo.com');
insert into employee (id, name, birthday, email) values (76, 'Nev Lindwall', '2007-10-09', null);
insert into employee (id, name, birthday, email) values (77, 'Portie Blackshaw', '1994-08-24', null);
insert into employee (id, name, birthday, email) values (78, 'Noah Milbourn', '2006-09-10', 'nmilbourn25@sphinn.com');
insert into employee (id, name, birthday, email) values (79, 'Hyatt Alenichev', '1996-02-04', 'halenichev26@webs.com');
insert into employee (id, name, birthday, email) values (80, 'Rois Sambidge', '1987-09-06', 'rsambidge27@google.de');
insert into employee (id, name, birthday, email) values (81, 'Welsh Kennerknecht', '1991-10-30', 'wkennerknecht28@facebook.com');
insert into employee (id, name, birthday, email) values (82, 'Stephenie Edgell', '1984-08-27', 'sedgell29@google.it');
insert into employee (id, name, birthday, email) values (83, 'Cole Sainsberry', '2012-06-08', 'csainsberry2a@skyrock.com');
insert into employee (id, name, birthday, email) values (84, 'Farrand Markovich', '2007-05-08', 'fmarkovich2b@shinystat.com');
insert into employee (id, name, birthday, email) values (85, 'Isaak Vittori', '1991-04-18', 'ivittori2c@goo.ne.jp');
insert into employee (id, name, birthday, email) values (86, 'Scotti De Bruijn', '2007-11-02', null);
insert into employee (id, name, birthday, email) values (87, 'Mellie Matus', '1985-12-19', 'mmatus2e@artisteer.com');
insert into employee (id, name, birthday, email) values (88, 'Hana Henrych', '2009-07-24', 'hhenrych2f@nationalgeographic.com');
insert into employee (id, name, birthday, email) values (89, 'Conney Union', '2015-01-05', 'cunion2g@nymag.com');
insert into employee (id, name, birthday, email) values (90, 'Georgie Colliber', '1989-03-16', 'gcolliber2h@miitbeian.gov.cn');
insert into employee (id, name, birthday, email) values (91, 'Maitilde Gladeche', '1999-08-03', 'mgladeche2i@histats.com');
insert into employee (id, name, birthday, email) values (92, 'Eddie Camerana', '1990-02-26', 'ecamerana2j@gov.uk');
insert into employee (id, name, birthday, email) values (93, 'Barb Daenen', '1988-07-20', 'bdaenen2k@moonfruit.com');
insert into employee (id, name, birthday, email) values (94, 'Hugh Jatczak', '2008-10-28', 'hjatczak2l@adobe.com');
insert into employee (id, name, birthday, email) values (95, 'Niko Storms', '2006-11-04', 'nstorms2m@printfriendly.com');
insert into employee (id, name, birthday, email) values (96, 'Margarita Rene', null, 'mrene2n@dion.ne.jp');
insert into employee (id, name, birthday, email) values (97, 'Delores Needs', '1984-09-20', null);
insert into employee (id, name, birthday, email) values (98, 'Woodman Tomkys', '1980-06-26', 'wtomkys2p@jigsy.com');
insert into employee (id, name, birthday, email) values (99, 'Cordula Mohring', '2009-03-08', 'cmohring2q@1688.com');
insert into employee (id, name, birthday, email) values (100, 'Jodi Roffey', '1977-10-22', 'jroffey2r@statcounter.com');
--3. Sütunların her birine göre diğer sütunları güncelleyecek 5 adet UPDATE işlemi yapalım.
UPDATE employee SET name = 'Cemile Karabulut' WHERE id = 1;
UPDATE employee SET id = 1 WHERE name ILIKE 'c%';
UPDATE employee SET email = null WHERE birthday < (now() - '10 years'::interval);
UPDATE employee SET birthday = now() WHERE email LIKE '%net%';
UPDATE employee SET name = null WHERE id BETWEEN 4 AND 10;
--4. Sütunların her birine göre ilgili satırı silecek 5 adet DELETE işlemi yapalım.
DELETE FROM employee WHERE id > 50;
DELETE FROM employee WHERE name LIKE 'R%';
DELETE FROM employee WHERE birthday BETWEEN '1999-01-01' AND '2005-01-01';
DELETE FROM employee WHERE email LIKE '%.com';
DELETE FROM employee WHERE id IN (1,3,5);
